Repository les-crepes/CAREOT_APP, pull requests merged in 2022-09, with the labels that each got.

#103 Auth fix
  lib/model/client.dart
  lib/provider/auth_provider.dart
Labels: bug, frontend

#104 clients for dietitian
  lib/api/firebase_api.dart
  lib/api/firebase_client.dart
  lib/api/iclient.dart
  lib/model/client.dart
  test/client_test.dart
Labels: enhancement, backend

#98 created a user class from which client and diet inherit from
  lib/api/firebase_user.dart
  lib/api/iclient.dart
  lib/api/iuser.dart
  lib/main.dart
  lib/model/dietitian.dart
  lib/model/user.dart
  lib/provider/auth_provider.dart
  test/client_test.dart
  test/dietitian_test.dart
  test/meal_test.dart
Labels: enhancement, backend

#112 changed type
  lib/model/meal.dart
Labels: backend

#114 AUTH test
  lib/api/firebase_connection.dart
  lib/api/iauth.dart
  pubspec.lock
  pubspec.yaml
  test/auth_test.dart
Labels: enhancement, backend

#126 Get AfterCare of Client
  .vscode/launch.json
  lib/api/firebase_aftercare.dart
  lib/api/iaftercare.dart
  lib/model/aftercare.dart
  lib/scripts/populate_db.dart
  test/aftercare_test.dart
Labels: enhancement, backend

#124 85 mealprovider
  lib/api/firebase_meal.dart
  lib/api/imeal.dart
  lib/main.dart
  lib/model/meal.dart
  lib/provider/auth_provider.dart
  lib/provider/meal_provider.dart
  lib/router/home_guard.dart
  lib/router/router.dart
  lib/router/router.gr.dart
  lib/screens/add_meal.dart
  lib/screens/diary.dart
  pubspec.lock
Labels: enhancement, frontend

#125 Read Dietitian of Client
  lib/api/firebase_dietitian.dart
  lib/api/idietitian.dart
  test/dietitian_test.dart
Labels: enhancement, backend

#134 CLIENT + DIET => USER
  lib/api/firebase_connection.dart
  lib/api/firebase_dietitian.dart
  lib/api/firebase_user.dart
  lib/api/iauth.dart
  lib/api/idietitian.dart
  lib/api/iuser.dart
  lib/model/dietitian.dart
  lib/model/user.dart
  lib/scripts/populate_db.dart
  test/dietitian_test.dart
  test/user_test.dart
Labels: enhancement, backend

#128 115 ajouter email dans user model
  lib/api/firebase_user.dart
  lib/model/user.dart
  lib/provider/client_provider.dart
  lib/scripts/populate_db.dart
  test/aftercare_test.dart
  test/meal_test.dart
  test/user_test.dart
Labels: enhancement, backend

#135 Message On listen
  lib/api/firebase_message.dart
Labels: enhancement, backend

#142 Client vs Diet
  lib/provider/auth_provider.dart
  lib/router/chat_guard.dart
  lib/router/home_guard.dart
Labels: enhancement, frontend

#139 Data populated
  lib/scripts/populate_db.dart
  pubspec.lock
Labels: enhancement, backend

#137 52 amelioration page register
  lib/api/firebase_user.dart
  lib/api/iuser.dart
  lib/main.dart
  lib/provider/auth_provider.dart
  lib/provider/register_provider.dart
  lib/router/router.dart
  lib/router/router.gr.dart
  lib/screens/register.dart
  lib/widgets/forms/main_text_field.dart
  lib/widgets/register/register_first_page.dart
  lib/widgets/register/register_second_page.dart
  lib/widgets/register/register_third_page.dart
Labels: enhancement, frontend

#144 new login
  lib/screens/login.dart
Labels: enhancement, frontend

#146 145 fix guards
  lib/main.dart
  lib/provider/auth_provider.dart
  lib/router/router.dart
  lib/router/router.gr.dart
  lib/screens/login.dart
  lib/screens/profile.dart
  lib/screens/register.dart
  lib/widgets/register/register_third_page.dart
  pubspec.lock
Labels: bug, frontend

#149 133 créer page modification dossier client
  lib/api/firebase_aftercare.dart
  lib/provider/aftercare_provider.dart
  lib/provider/client_provider.dart
  lib/router/router.dart
  lib/router/router.gr.dart
  lib/screens/client_list.dart
  lib/screens/client_record.dart
  lib/screens/update_client_record.dart
  lib/widgets/custom_list.dart
  lib/widgets/forms/date_picker.dart
  lib/widgets/forms/main_text_field.dart
  lib/widgets/profile_template.dart
  lib/widgets/straight_top_bar.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, frontend

#150 88 intégrer backend dans page profile
  android/app/src/main/AndroidManifest.xml
  lib/api/firebase_connection.dart
  lib/api/firebase_user.dart
  lib/api/iuser.dart
  lib/provider/auth_provider.dart
  lib/screens/diary.dart
  lib/screens/profile.dart
  test/user_test.dart
  widgetbook/widgetbook.dart
Labels: enhancement, frontend

#154 Fix bug clavier
  lib/screens/login.dart
  lib/screens/register.dart
Labels: bug, frontend

#158 Rotation bloqué
  lib/main.dart
Labels: enhancement, frontend

#157 LoadingOverlay done
  lib/provider/register_provider.dart
  lib/screens/login.dart
  lib/screens/register.dart
  lib/widgets/loading_overlay.dart
  lib/widgets/register/register_third_page.dart
Labels: enhancement, frontend

#160 151 ajouter backend dans addmeal et modification
  lib/api/firebase_meal.dart
  lib/api/imeal.dart
  lib/provider/meal_provider.dart
  lib/router/router.gr.dart
  lib/screens/add_meal.dart
  lib/screens/diary.dart
  lib/screens/login.dart
Labels: enhancement, frontend

#148 Firebase Storage
  lib/api/firebase_document.dart
  lib/api/ifile.dart
  lib/main.dart
  lib/screens/diary.dart
  pubspec.lock
  pubspec.yaml
  test/file_test.dart
  test/test.txt
Labels: enhancement, backend

#170 162 add client to dietitian
  .github/workflows/continuousDeployment.yml
  .vscode/launch.json
  lib/api/firebase_user.dart
  lib/api/iuser.dart
  lib/model/meal.dart
  lib/model/user.dart
  lib/scripts/app_run.dart
  pubspec.lock
  test/user_test.dart
Labels: enhancement, backend

#169 159 afficher les chats du diététicien
  lib/api/firebase_message.dart
  lib/api/imessage.dart
  lib/model/custom_list_tile_data.dart
  lib/model/user.dart
  lib/provider/chat_provider.dart
  lib/router/chat_guard.dart
  lib/router/chat_router_page.dart
  lib/router/router.dart
  lib/router/router.gr.dart
  lib/screens/chat.dart
  lib/screens/client_record.dart
  lib/screens/discussion_list.dart
  lib/screens/home.dart
  lib/screens/login.dart
  lib/widgets/custom_list.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, frontend

#164 161 vue readonly du calendrier pour les diététiciens
  lib/router/router.gr.dart
  lib/screens/add_meal.dart
  lib/screens/client_record.dart
  lib/screens/diary.dart
  lib/widgets/diary/diary_top_bar.dart
  pubspec.lock
Labels: enhancement, frontend

#175 Envoi de message
  .github/workflows/super-linter.yml
  lib/api/firebase_message.dart
  lib/api/imessage.dart
  lib/provider/chat_provider.dart
  lib/router/chat_router_page.dart
  lib/screens/chat.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, frontend

#177 176 file transfer 1
  android/app/proguard-rules.pro
  lib/provider/chat_provider.dart
  lib/router/chat_router_page.dart
  lib/screens/chat.dart
  pubspec.lock
  pubspec.yaml
  widgetbook/widgetbook.dart
Labels: enhancement, frontend

#178 165 correction login
  lib/api/exceptions.dart
  lib/api/firebase_connection.dart
  lib/api/iauth.dart
  lib/provider/auth_provider.dart
  lib/screens/login.dart
Labels: enhancement, frontend

#182 Implémenter backend dans liste de fichiers
  lib/provider/chat_provider.dart
  lib/router/router.gr.dart
  lib/screens/chat.dart
  lib/screens/document_list.dart
Labels: enhancement, frontend

#184 better chat topbar
  lib/screens/chat.dart
Labels: enhancement, frontend

#190 180 ajouter logo sur login
  assets/images/logo.svg
  assets/images/mascotte.svg
  assets/images/title.svg
  lib/screens/login.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, frontend

#192 Navbar style
  lib/widgets/navbar.dart
Labels: enhancement, frontend

#193 Add birthday field
  lib/screens/update_client_record.dart
  lib/widgets/forms/date_picker.dart
  lib/widgets/register/register_second_page.dart
  pubspec.lock
Labels: enhancement, frontend

#191 167 ajouter photos dans firebase
  assets/images/default_user_pic.jpeg
  lib/api/firebase_user.dart
  lib/main.dart
  lib/provider/auth_provider.dart
  lib/provider/meal_provider.dart
  lib/router/router.dart
  lib/router/router.gr.dart
  lib/screens/add_meal.dart
  lib/screens/chat.dart
  lib/screens/client_list.dart
  lib/screens/client_record.dart
  lib/screens/diary.dart
  lib/screens/discussion_list.dart
  lib/screens/profile.dart
  lib/widgets/cards/arrow_pic_card.dart
  lib/widgets/cards/pic_card.dart
  lib/widgets/diary/diary_top_bar.dart
  lib/widgets/profile/profile_top_bar.dart
  lib/widgets/profile_avatar.dart
  lib/widgets/profile_template.dart
  lib/widgets/register/register_third_page.dart
  pubspec.lock
  pubspec.yaml
  widgetbook/widgetbook.dart
Labels: enhancement, frontend

#194 documentation technique 1
  .github/architecture.drawio.svg
  README.md
Labels: documentation

#203 real data
  lib/scripts/populate_db.dart
Labels: enhancement, backend

#204 Transitions fixed
  lib/router/router.dart
  lib/router/router.gr.dart
  lib/screens/add_meal.dart
  lib/screens/client_record.dart
  lib/screens/diary.dart
  lib/screens/document_list.dart
  lib/screens/update_client_record.dart
  lib/widgets/register/register_second_page.dart
Labels: enhancement, frontend

#206 171 obliger les nouveaux clients à avoir un diét
  .env
  lib/main.dart
  lib/provider/auth_provider.dart
  lib/provider/register_provider.dart
  lib/widgets/register/register_first_page.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, frontend

#207 Chat button fixed
  lib/router/router.dart
  lib/router/router.gr.dart
  lib/screens/client_record.dart
  lib/screens/home.dart
Labels: enhancement, frontend

#210 sticky header
  lib/screens/diary.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, frontend

#211 201 correction vue diary
  lib/api/firebase_meal.dart
  lib/api/imeal.dart
  lib/provider/chat_provider.dart
  lib/provider/meal_provider.dart
  lib/screens/diary.dart
Labels: bug, frontend

#217 Fix bug
  lib/provider/meal_provider.dart
  lib/screens/add_meal.dart
Labels: bug, frontend

#213 212 correction bug liste discussion
  lib/api/firebase_user.dart
  lib/api/iuser.dart
  lib/provider/client_provider.dart
  lib/screens/client_list.dart
Labels: bug, frontend

#215 214 actualisation en direct du diary client
  lib/api/firebase_meal.dart
  lib/api/imeal.dart
  lib/provider/meal_provider.dart
  lib/screens/diary.dart
Labels: bug, frontend

#220 Change format
  lib/widgets/custom_list.dart
Labels: bug, frontend

#222 Fix ok
  lib/provider/chat_provider.dart
  lib/widgets/custom_list.dart
Labels: bug, frontend

#225 Comments + App Icon
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/drawable-hdpi/ic_launcher_background.png
  android/app/src/main/res/drawable-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/drawable-mdpi/ic_launcher_background.png
  android/app/src/main/res/drawable-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/drawable-xhdpi/ic_launcher_background.png
  android/app/src/main/res/drawable-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/drawable-xxhdpi/ic_launcher_background.png
  android/app/src/main/res/drawable-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/drawable-xxxhdpi/ic_launcher_background.png
  android/app/src/main/res/drawable-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-anydpi-v26/launcher_icon.xml
  android/app/src/main/res/mipmap-hdpi/launcher_icon.png
  android/app/src/main/res/mipmap-mdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xhdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xxhdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xxxhdpi/launcher_icon.png
  assets/icon/ic_launcher.png
  assets/icon/ic_launcher_adaptive_back.png
  assets/icon/ic_launcher_adaptive_fore.png
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  lib/main.dart
  lib/provider/aftercare_provider.dart
  lib/provider/auth_provider.dart
  lib/provider/chat_provider.dart
  lib/provider/client_provider.dart
  lib/provider/meal_provider.dart
  lib/provider/register_provider.dart
  lib/router/router.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, frontend

#227 File size is now showing in chat
  lib/screens/chat.dart
Labels: enhancement, frontend

#223 185 exceptions
  lib/api/exceptions.dart
  lib/api/firebase_aftercare.dart
  lib/api/firebase_api.dart
  lib/api/firebase_connection.dart
  lib/api/firebase_file.dart
  lib/api/firebase_meal.dart
  lib/api/firebase_message.dart
  lib/api/firebase_user.dart
  lib/api/iauth.dart
  pubspec.lock
Labels: enhancement, backend

#229 fix avatar
  lib/screens/add_meal.dart
  lib/widgets/custom_cached_network_image.dart
Labels: enhancement, frontend
