Repository les-crepes/CAREOT_APP, pull requests merged in 2022-08, with the labels that each got.

#19 api structure
  lib/api/api.dart
  lib/api/firebase_api.dart
Labels: enhancement

#27 Widgetbook ready to use
  .vscode/launch.json
  pubspec.lock
  pubspec.yaml
  widgetbook/main.dart
  widgetbook/widgetbook.dart
Labels: documentation, frontend

#29 21 api client
  lib/api/api.dart
  lib/api/firebase_api.dart
  lib/model/client.dart
Labels: enhancement, backend

#30 Added ThemeData
  lib/main.dart
  lib/theme.dart
  widgetbook/widgetbook.dart
Labels: enhancement, frontend

#31 CRUD aftercare
  lib/api/api.dart
  lib/api/firebase_api.dart
  lib/model/aftercare.dart
Labels: enhancement, backend

#34 Document CRUD
  lib/api/api.dart
  lib/api/firebase_api.dart
  lib/model/document.dart
Labels: enhancement, backend

#36 10 créer le composant bouton accueil
  lib/widgets/gradient_button.dart
  lib/widgets/right_arrow_button.dart
  widgetbook/widgetbook.dart
Labels: enhancement, frontend

#33 25 api dietician
  lib/api/api.dart
  lib/api/firebase_api.dart
  lib/model/dietitian.dart
Labels: enhancement, backend

#37 2 configurer firebase auth
  lib/api/auth.dart
  lib/api/firebase_connection.dart
  lib/main.dart
Labels: enhancement, backend

#28 Add text form field
  .github/workflows/super-linter.yml
  lib/main.dart
  lib/widgets/forms/main_text_field.dart
  test/default_test.dart
  widgetbook/widgetbook.dart
Labels: enhancement, frontend

#38 11 page de login
  .vscode/settings.json
  android/app/build.gradle
  lib/main.dart
  lib/screens/login.dart
  lib/widgets/login/bottom_shape.dart
  lib/widgets/login/top_shape.dart
  lib/widgets/right_arrow_button.dart
  widgetbook/widgetbook.dart
Labels: enhancement, frontend

#40 CRUD meal
  lib/api/api.dart
  lib/api/firebase_api.dart
  lib/model/meal.dart
Labels: enhancement, backend

#43 CD test
  lib/main.dart
Labels: enhancement, frontend

#45 12 page de register
  lib/screens/register.dart
  lib/widgets/register/bottom_shape.dart
  lib/widgets/register/top_shape.dart
  widgetbook/widgetbook.dart
Labels: enhancement, frontend

#55 REFACTORED
  lib/api/api.dart
  lib/api/firebase_aftercare.dart
  lib/api/firebase_api.dart
  lib/api/firebase_client.dart
  lib/api/firebase_connection.dart
  lib/api/firebase_dietitian.dart
  lib/api/firebase_document.dart
  lib/api/firebase_meal.dart
  lib/api/firebase_message.dart
  lib/api/iaftercare.dart
  lib/api/iauth.dart
  lib/api/iclient.dart
  lib/api/idietitian.dart
  lib/api/idocument.dart
  lib/api/imeal.dart
  lib/api/imessage.dart
Labels: backend

#57 Message screen
  lib/router/router.dart
  lib/router/router.gr.dart
  lib/screens/chat.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  widgetbook/widgetbook.dart
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: enhancement, frontend

#60 4 configurer firebase realtime database
  android/app/google-services.json
  lib/api/firebase_message.dart
  lib/main.dart
  lib/model/message.dart
Labels: help wanted

#61 messages CRUD + model
  lib/api/firebase_message.dart
  lib/main.dart
  lib/model/message.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, backend

#69 API refactored to include basic unit tests and factorisation
  lib/api/firebase_aftercare.dart
  lib/api/firebase_client.dart
  lib/api/firebase_dietitian.dart
  lib/api/firebase_meal.dart
  lib/api/firebase_message.dart
  lib/api/idocument.dart
  lib/main.dart
  lib/model/aftercare.dart
  lib/model/client.dart
  lib/model/dietitian.dart
  lib/model/document.dart
  lib/model/imodel.dart
  lib/model/meal.dart
  lib/model/message.dart
  test/aftercare_test.dart
  test/client_test.dart
  test/default_test.dart
  test/dietitian_test.dart
  test/meal_test.dart
  test/message_test.dart
Labels: enhancement, help wanted, backend

#78 66 créer la page add meal
  assets/images/placeholderfood.png
  lib/main.dart
  lib/router/router.dart
  lib/router/router.gr.dart
  lib/screens/add_meal.dart
  lib/screens/diary.dart
  lib/screens/home.dart
  lib/screens/login.dart
  lib/widgets/buttons/action_button.dart
  lib/widgets/cards/main_card.dart
  lib/widgets/custom_icon_button.dart
  lib/widgets/forms/main_text_field.dart
  lib/widgets/slider_with_text.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, frontend

#83 73 créer la page de profile
  assets/images/default_user_pic.png
  assets/images/other_profile_pic.png
  lib/screens/add_meal.dart
  lib/screens/profile.dart
  lib/theme.dart
  lib/widgets/buttons/custom_icon_button.dart
  lib/widgets/cards/arrow_pic_card.dart
  lib/widgets/cards/left_element_card.dart
  lib/widgets/cards/pic_card.dart
  lib/widgets/diary/diary_top_bar.dart
  lib/widgets/profile/profile_top_bar.dart
  lib/widgets/profile/top_shape.dart
  lib/widgets/profile_avatar.dart
  lib/widgets/text_information.dart
  widgetbook/widgetbook.dart
Labels: enhancement, frontend

#84 81 auth guard
  lib/main.dart
  lib/provider/auth_provider.dart
  lib/router/auth_gard.dart
  lib/router/router.dart
  lib/router/router.gr.dart
  lib/screens/login.dart
  lib/screens/profile.dart
  lib/widgets/profile/profile_top_bar.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, frontend

#92 91 modify datatypes to have required fields where needed
  lib/model/aftercare.dart
  lib/model/client.dart
  lib/model/dietitian.dart
  lib/model/meal.dart
  lib/model/message.dart
  lib/screens/diary.dart
  test/aftercare_test.dart
  test/client_test.dart
  test/dietitian_test.dart
  test/meal_test.dart
  test/message_test.dart
  widgetbook/widgetbook.dart
Labels: enhancement, backend

#95 89 liste de discussions
  lib/main.dart
  lib/model/custom_list_tile_data.dart
  lib/router/chat_guard.dart
  lib/router/router.dart
  lib/router/router.gr.dart
  lib/screens/discussion_list.dart
  lib/screens/home.dart
  lib/widgets/badge.dart
  lib/widgets/custom_list.dart
Labels: enhancement, frontend

#100 Added scaffold
  lib/screens/login.dart
  lib/screens/register.dart
  pubspec.lock
Labels: bug, frontend
